the mesa run folder is /work/al363/runs/low_overhead/runs_x100_1_2

starting from 0
DATE: 2021-04-12
TIME: 21:44:35
                                         version_number       10108
 read /hpc/group/physics/al363/low_overhead/sens/base/inlist_base
At line 1848 of file ../private/ctrls_io.f90 (unit = 30, file = 'inlist_cluster')
Fortran runtime error: End of file

Error termination. Backtrace:
#0  0x7f260efff870 in nml_get_obj_data
	at /root/mesasdk-src/gcc/libgfortran/io/list_read.c:3529
#1  0x7f260f007dec in finalize_transfer
	at /root/mesasdk-src/gcc/libgfortran/io/transfer.c:3891
#2  0x489864 in __ctrls_io_MOD_read_controls_file
	at ../private/ctrls_io.f90:1848
#3  0x489bb4 in __ctrls_io_MOD_read_controls_file
	at ../private/ctrls_io.f90:1893
#4  0x489d27 in __ctrls_io_MOD_read_controls
	at ../private/ctrls_io.f90:1804
#5  0x489d95 in __ctrls_io_MOD_do_one_setup
	at ../private/ctrls_io.f90:1774
#6  0x437705 in __run_star_support_MOD_before_evolve_loop
	at ../job/run_star_support.f90:277
#7  0x438108 in __run_star_support_MOD_run1_star
	at ../job/run_star_support.f90:94
#8  0x41c710 in __run_star_MOD_do_run_star
	at /hpc/group/physics/al363/mesa10108/star/job/run_star.f:26
#9  0x41c761 in run
	at ../src/run.f:13
#10  0x41c798 in main
	at ../src/run.f:2
 read inlist_cluster




Failed while trying to read control namelist file: inlist_cluster
Perhaps the following runtime error message will help you find the problem.

DATE: 2021-04-12
TIME: 21:44:37
